// src/lib/List.svelte
<script>
  import Meal from './Meal.svelte';
  export let list = {};
</script>

<div>
  <h2>{list.mealKindName}</h2>

  {#each list.rows as lunch}
    <Meal
      name={lunch.item.mealName}
      price={lunch.item.price}
      available={lunch.item.state == 0}
    />
  {/each}
</div>

<style>
  h2 {
    font-size: 22px;
    margin: 0;
    padding: 20px 0 8px;
  }
</style>

// src/components/List.vue
<template>
    <div>
        <h2>{{ this.list.mealKindName }}</h2>
        <Meal
            v-for="lunch in list.rows"
            :key="lunch.item.altId"
            :name="lunch.item.mealName"
            :price="lunch.item.price"
            :available="lunch.item.state == 0"
        >
        </Meal>
    </div>
</template>

<script>
import Meal from './Meal.vue';

export default {
    props: {
        list: {
            type: Object,
            required: true,
        },
    },
    components: {
        Meal,
    },
};
</script>

<style>
h2 {
    font-size: 22px;
    margin: 0;
    padding: 32px 8px 8px;
}
</style>
