// src/App.vue
<script>
import List from './components/List.vue';

export default {
  data() {
    return {
      menu: null,
    };
  },
  components: {
    List,
  },
  created() {
    fetch('https://doctus.creativnivyvojari.cz/app/index.php')
      .then((response) => response.json())
      .then((json) => (this.menu = json.groups));
  },
};
</script>

<template>
  <div v-if="this.menu != null">
    <List :list="this.menu[0]"></List>

    <List :list="this.menu[1]"></List>

    <List :list="this.menu[2]"></List>

    <List :list="this.menu[3]"></List>
  </div>
</template>

<style>
@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap');
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  height: 100vh;
}

#app {
  font-family: 'Rubik', Avenir, Helvetica, Arial, sans-serif;
  font-size: 14px;
  background-color: #fafafa;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: black;

  height: 100vh;
  padding: 16px;
}

#app > div {
  margin: 0 auto;
  max-width: 1100px;
}
</style>

// src/App.svelte
<script>
	import List from './lib/List.svelte'

	let menu = null,
		date = null

	fetch('https://doctus.creativnivyvojari.cz/app/index.php')
		.then((response) => response.json())
		.then((json) => {
			menu = json.groups
			date = new Date(json.date)
		})
</script>

{#if date != null}
	<div>
		<h1 id="date">
			{date.toLocaleDateString('cs-CZ', {
				weekday: 'long',
				year: 'numeric',
				month: 'short',
				day: 'numeric',
			})}
		</h1>
		{#if menu.length > 0}
			<div>
				<List list={menu[0]} />

				<List list={menu[1]} />

				<List list={menu[2]} />

				<List list={menu[3]} />
			</div>
		{:else}
			<div>
				<h3>Na dnešek není připraveno žádné menu</h3>
			</div>
		{/if}
	</div>
{/if}

<style global>
	@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap');
	* {
		box-sizing: border-box;
	}

	:global(body) {
		margin: 0;
		background-color: #fafafa;
	}

	:global(#app) {
		font-family: 'Rubik', Avenir, Helvetica, Arial, sans-serif;
		font-size: 14px;
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;
		color: black;

		padding: 16px 16px 100px;
	}

	:global(#app > div) {
		margin: 0 auto;
		max-width: 1100px;
	}

	#date {
		margin: 32px 0 0;
		text-transform: capitalize;
	}
</style>
